# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('website_link', models.CharField(max_length=255, verbose_name='Web sitesi linki')),
                ('appstore_link', models.CharField(max_length=255, verbose_name='Appstore linki')),
                ('playstore_link', models.CharField(max_length=255, verbose_name='Playstore linki')),
                ('icon', models.ImageField(upload_to='', verbose_name='İkon')),
                ('app_image', models.ImageField(upload_to='', verbose_name='Uygulama resmi')),
                ('background_image', models.ImageField(upload_to='', verbose_name='Arkaplan resmi')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
