# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_app_yayinlanma_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='app',
            name='background_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', verbose_name='Arkaplan resmi', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='app',
            name='yayinlanma_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yayınlanma Tarihi'),
        ),
    ]
