# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170707_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='images/testimagemodel/', verbose_name='Image', width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
            ],
            options={
                'verbose_name': 'Image Example',
                'verbose_name_plural': 'Image Examples',
            },
        ),
    ]
