# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170710_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='height',
        ),
        migrations.RemoveField(
            model_name='app',
            name='width',
        ),
        migrations.AlterField(
            model_name='app',
            name='background_image',
            field=models.ImageField(upload_to='', verbose_name='Arka plan'),
        ),
    ]
