# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 10:07
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170710_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
    ]
