# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 10:49
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_app_ppoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='height',
        ),
        migrations.RemoveField(
            model_name='app',
            name='ppoi',
        ),
        migrations.RemoveField(
            model_name='app',
            name='width',
        ),
        migrations.AlterField(
            model_name='app',
            name='background_image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='', verbose_name='Arkaplan resmi'),
        ),
    ]
