# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170710_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='background_image',
            field=models.ImageField(height_field='height', upload_to='', verbose_name='Arkaplan resmi', width_field='width'),
        ),
    ]
