# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
