# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_auto_20170720_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='avatar',
            field=models.ImageField(height_field='height', upload_to='', verbose_name='Fotoğraf (370x370)', width_field='width'),
        ),
    ]
