# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_auto_20170720_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height (370)'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width (370)'),
        ),
    ]
