# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_auto_20170720_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Enlem'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Boylam'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='active',
            field=models.BooleanField(verbose_name='Active'),
        ),
    ]
