# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_auto_20170720_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='color',
            field=models.CharField(blank=True, max_length=6, verbose_name='Menü Arkaplan Rengi'),
        ),
    ]
