# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0011_auto_20170720_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='footer_social_facebook',
            field=models.TextField(blank=True, null=True, verbose_name='Facebook link'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='footer_social_twitter',
            field=models.TextField(blank=True, null=True, verbose_name='Twitter link'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='footer_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Footer Başlık'),
        ),
    ]
