# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0012_auto_20170721_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='footer_social_facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='footer_social_twitter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter link'),
        ),
    ]
