# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0013_auto_20170721_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='directions',
            field=models.TextField(blank=True, null=True, verbose_name='Yol Tarifi'),
        ),
    ]
