# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0017_auto_20170726_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='form_active',
            field=models.BooleanField(default=True, verbose_name='Form aktifliği'),
        ),
    ]
