# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0019_auto_20170731_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='facebook_link',
        ),
        migrations.AddField(
            model_name='committee',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Linkedin link'),
        ),
    ]
